AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  SAM Template to create a Lambda function for POST requests to the Student DynamoDB table

Resources:
  StudentPostFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: src/post_names.js
      Environment:
        Variables:
          TABLE_NAME: !ImportValue SStudentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue StudentTable
      Events:
        PostStudentApi:
          Type: Api
          Properties:
            Path: /students
            Method: post

  StudentGetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: src/get_names.js
      Environment:
        Variables:
          TABLE_NAME: !ImportValue StudentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue StudentTable
      Events:
        GetStudentApi:
          Type: Api
          Properties:
            Path: /students/{studentId}
            Method: get

Outputs:
  StudentGetApiUrl:
    Description: "API Gateway endpoint URL for the Student GET function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/students/{studentId}"
    Export:
      Name: StudentGetApiUrl 
  
  StudentPostApiUrl:
    Description: "API Gateway endpoint URL for the Student POST function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/students"
    Export:
      Name: StudentPostApiUrl