yamlAWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  SAM Template to create a Lambda function for POST requests to a DynamoDB table

Resources:
  LambdaPostFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: src/
      Environment:
        Variables:
          TABLE_NAME: !ImportValue itemsDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue itemsDB
      Events:
        PostApi:
          Type: Api
          Properties:
            Path: /items
            Method: post

  GetItemsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: src/
      Environment:
        Variables:
          TABLE_NAME: !ImportValue itemsDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue itemsDB
      Events:
        GetItemsApi:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: get

Outputs:
  GetItemsApiUrl:
    Description: "API Gateway endpoint URL for the GET function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items/{id}"
    Export:
      Name: GetItemsApiUrl

  LambdaPostApiUrl:
    Description: "API Gateway endpoint URL for the POST function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"
    Export:
      Name: LambdaPostApiUrl