AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  HelloWorldApp

  Sample SAM Template for HelloWorldApp

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/index.js
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        TestApi:
          Type: Api
          Properties:
            Path: /test
            Method: get
  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt HelloWorldFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn:
        - 'arn:aws:execute-api:ap-south-1:058264479354:svvu88js31/*/GET/hello'
        - 'arn:aws:execute-api:ap-south-1:058264479354:svvu88js31/*/GET/test'

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for HelloWorld function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  HelloWorldFunction:
    Description: "HelloWorld Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn